/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* Now using environment variables for security */

export const projectId = import.meta.env.VITE_SUPABASE_URL?.replace('https://', '').replace('.supabase.co', '') || 'nbizzgetxskphtltxnva';
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iaXp6Z2V0eHNrcGh0bHR4bnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMDMyODYsImV4cCI6MjA3NDg3OTI4Nn0.1gczm8kqvldopwUYX6NkY-XZ9cEUn4sw5ueSuZg88D0';
